# Flutter engine/plugin entry points are generated by the Flutter tool.
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.util.** { *; }
-keep class io.flutter.view.** { *; }
-keep class io.flutter.embedding.** { *; }
-keep class io.flutter.plugins.** { *; }

# Keep your Activity class name stable for Android startup.
-keep class com.example.OdoCart.MainActivity { *; }
